const COMMENT_VISIBILITY = Object.freeze({
  PUBLIC: 'PUBLIC',
  INTERNAL: 'INTERNAL',
});

const COMMENT_VISIBILITY_VALUES = Object.values(COMMENT_VISIBILITY);
const MAX_COMMENT_LENGTH = 2000;

module.exports = { COMMENT_VISIBILITY, COMMENT_VISIBILITY_VALUES, MAX_COMMENT_LENGTH };