const ROLES = Object.freeze({
  STUDENT: 'STUDENT',
  STAFF: 'STAFF',
  MANAGER: 'MANAGER',
});
const ROLE_VALUES = Object.values(ROLES);

const CATEGORIES = ['Fees', 'Attendance', 'ID Card', 'Documents', 'Certificates', 'Other'];

const PRIORITIES = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'];
const PRIORITY_RANK = { CRITICAL: 1, HIGH: 2, MEDIUM: 3, LOW: 4 };
const DEFAULT_PRIORITY = 'MEDIUM';

const STATUSES = Object.freeze({
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_FOR_STUDENT: 'WAITING_FOR_STUDENT',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REOPENED: 'REOPENED',
});
const STATUS_VALUES = Object.values(STATUSES);
const ACTIVE_STATUSES = [
  STATUSES.OPEN,
  STATUSES.IN_PROGRESS,
  STATUSES.WAITING_FOR_STUDENT,
  STATUSES.REOPENED,
];
const FINISHED_STATUSES = [STATUSES.RESOLVED, STATUSES.CLOSED];

// Allowed status transitions (from -> [to, ...])
const STATUS_TRANSITIONS = {
  OPEN: ['IN_PROGRESS'],
  IN_PROGRESS: ['WAITING_FOR_STUDENT', 'RESOLVED'],
  WAITING_FOR_STUDENT: ['IN_PROGRESS', 'RESOLVED'],
  RESOLVED: ['CLOSED', 'IN_PROGRESS'],
  CLOSED: ['REOPENED'],
  REOPENED: ['IN_PROGRESS'],
};

// Transitions a student may perform on their own tickets ("from>to")
const STUDENT_TRANSITIONS = ['RESOLVED>CLOSED', 'RESOLVED>IN_PROGRESS', 'CLOSED>REOPENED'];
const STUDENT_REOPEN_WINDOW_DAYS = 7;

// PRODUCT ASSUMPTION: SLA durations are not specified by the assignment.
const SLA_HOURS = { CRITICAL: 2, HIGH: 8, MEDIUM: 24, LOW: 48 };
const SLA_AT_RISK_FRACTION = 0.25; // AT_RISK when 25% or less of the SLA window remains
const SLA_STATES = Object.freeze({
  ON_TRACK: 'ON_TRACK',
  AT_RISK: 'AT_RISK',
  BREACHED: 'BREACHED',
  MET: 'MET', // finished ticket resolved within SLA
});
const SLA_FILTER_VALUES = ['ON_TRACK', 'AT_RISK', 'BREACHED'];

const SORT_OPTIONS = ['newest', 'oldest', 'priority', 'sla_due'];

const ACTIVITY_ACTIONS = Object.freeze({
  TICKET_CREATED: 'TICKET_CREATED',
  TICKET_ASSIGNED: 'TICKET_ASSIGNED',
  TICKET_REASSIGNED: 'TICKET_REASSIGNED',
  PRIORITY_CHANGED: 'PRIORITY_CHANGED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  TICKET_RESOLVED: 'TICKET_RESOLVED',
  TICKET_CLOSED: 'TICKET_CLOSED',
  TICKET_REOPENED: 'TICKET_REOPENED',
  COMMENT_ADDED: 'COMMENT_ADDED',
});

module.exports = {
  ROLES,
  ROLE_VALUES,
  CATEGORIES,
  PRIORITIES,
  PRIORITY_RANK,
  DEFAULT_PRIORITY,
  STATUSES,
  STATUS_VALUES,
  ACTIVE_STATUSES,
  FINISHED_STATUSES,
  STATUS_TRANSITIONS,
  STUDENT_TRANSITIONS,
  STUDENT_REOPEN_WINDOW_DAYS,
  SLA_HOURS,
  SLA_AT_RISK_FRACTION,
  SLA_STATES,
  SLA_FILTER_VALUES,
  SORT_OPTIONS,
  ACTIVITY_ACTIONS,
};